import React, { Component } from "react"

const AboutUs = () => {

    return (
        <div className="container">
            <div className="row">
                <div className="col s12">
                    <h1 className="center">About</h1>
                    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec lorem mi, scelerisque in consequat id, hendrerit a felis. Morbi tincidunt orci id magna scelerisque, in rutrum ex accumsan. Quisque dapibus rhoncus commodo. In rutrum orci in est tempus, a malesuada purus malesuada. Sed mollis, odio eu laoreet pretium, justo nunc pulvinar libero, nec feugiat lectus arcu blandit nunc. Donec at metus pulvinar, interdum risus blandit, luctus nulla. Curabitur vitae diam augue. In at euismod nulla, nec elementum odio. Curabitur sodales nisi id justo viverra pretium eget sit amet arcu. Integer eget sem a odio blandit feugiat sed sit amet magna. Nulla facilisi. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec lorem mi, scelerisque in consequat id, hendrerit a felis. Morbi tincidunt orci id magna scelerisque, in rutrum ex accumsan. Quisque dapibus rhoncus commodo. In rutrum orci in est tempus, a malesuada purus malesuada. Sed mollis, odio eu laoreet pretium, justo nunc pulvinar libero, nec feugiat lectus arcu blandit nunc. Donec at metus pulvinar, interdum risus blandit, luctus nulla. Curabitur vitae diam augue. In at euismod nulla, nec elementum odio. Curabitur sodales nisi id justo viverra pretium eget sit amet arcu. Integer eget sem a odio blandit feugiat sed sit amet magna. Nulla facilisi. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec lorem mi, scelerisque in consequat id, hendrerit a felis. Morbi tincidunt orci id magna scelerisque, in rutrum ex accumsan. Quisque dapibus rhoncus commodo. In rutrum orci in est tempus, a malesuada purus malesuada. Sed mollis, odio eu laoreet pretium, justo nunc pulvinar libero, nec feugiat lectus arcu blandit nunc. Donec at metus pulvinar, interdum risus blandit, luctus nulla. Curabitur vitae diam augue. In at euismod nulla, nec elementum odio. Curabitur sodales nisi id justo viverra pretium eget sit amet arcu. Integer eget sem a odio blandit feugiat sed sit amet magna. Nulla facilisi.</p>
                    <h2 className="center">Our Story</h2>
                    <p>Vivamus eu lorem finibus, suscipit turpis ut, pellentesque nibh. Phasellus ultrices ligula sem. Cras commodo, lectus sed auctor pharetra, felis erat rutrum dui, non placerat enim ligula vel quam. Nullam tristique nec odio nec semper. Integer in dapibus sapien. Suspendisse potenti. Integer efficitur felis urna, sed molestie dolor sodales et. Duis finibus efficitur pretium. Aenean vitae dolor ac lorem commodo bibendum. Phasellus a ligula condimentum, consequat velit vitae, tempor ante. Nulla sit amet arcu et lacus rhoncus dapibus eget eu dolor. Pellentesque nec massa non tellus accumsan ullamcorper eu vel tortor. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec lorem mi, scelerisque in consequat id, hendrerit a felis. Morbi tincidunt orci id magna scelerisque, in rutrum ex accumsan. Quisque dapibus rhoncus commodo. In rutrum orci in est tempus, a malesuada purus malesuada. Sed mollis, odio eu laoreet pretium, justo nunc pulvinar libero, nec feugiat lectus arcu blandit nunc. Donec at metus pulvinar, interdum risus blandit, luctus nulla. Curabitur vitae diam augue. In at euismod nulla, nec elementum odio. Curabitur sodales nisi id justo viverra pretium eget sit amet arcu. Integer eget sem a odio blandit feugiat sed sit amet magna. Nulla facilisi. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec lorem mi, scelerisque in consequat id, hendrerit a felis. Morbi tincidunt orci id magna scelerisque, in rutrum ex accumsan. Quisque dapibus rhoncus commodo. In rutrum orci in est tempus, a malesuada purus malesuada. Sed mollis, odio eu laoreet pretium, justo nunc pulvinar libero, nec feugiat lectus arcu blandit nunc. Donec at metus pulvinar, interdum risus blandit, luctus nulla. Curabitur vitae diam augue. In at euismod nulla, nec elementum odio. Curabitur sodales nisi id justo viverra pretium eget sit amet arcu. Integer eget sem a odio blandit feugiat sed sit amet magna. Nulla facilisi.</p>
                </div>
            </div>
        </div>
    )
}

export { AboutUs }
